import 'dart:convert';
import 'dart:math';
import 'storage_backend.dart';

/// The 8 life dimensions tracked by the Life Score Dashboard.
enum LifeDimension {
  health('Health & Fitness', '🏃'),
  career('Career & Work', '💼'),
  finance('Finance & Wealth', '💰'),
  relationships('Relationships', '❤️'),
  fun('Fun & Recreation', '🎉'),
  growth('Personal Growth', '📚'),
  environment('Physical Environment', '🏠'),
  contribution('Contribution & Giving', '🤝');

  final String label;
  final String emoji;
  const LifeDimension(this.label, this.emoji);
}

/// A single assessment entry: scores for all 8 dimensions at a point in time.
class LifeScoreEntry {
  final DateTime date;
  final Map<LifeDimension, int> scores;
  final String? notes;

  LifeScoreEntry({
    required this.date,
    required this.scores,
    this.notes,
  });

  /// Overall score: average of all dimensions (0-10).
  double get overall =>
      scores.values.fold(0, (a, b) => a + b) / scores.length;

  /// Standard deviation — measures balance across dimensions.
  double get imbalance {
    final avg = overall;
    final variance =
        scores.values.fold(0.0, (a, v) => a + (v - avg) * (v - avg)) /
            scores.length;
    return sqrt(variance);
  }

  /// Dimensions scoring below average minus 1.5.
  List<LifeDimension> get weakSpots {
    final avg = overall;
    return scores.entries
        .where((e) => e.value < avg - 1.5)
        .map((e) => e.key)
        .toList();
  }

  /// Dimensions scoring above average plus 1.5.
  List<LifeDimension> get strengths {
    final avg = overall;
    return scores.entries
        .where((e) => e.value > avg + 1.5)
        .map((e) => e.key)
        .toList();
  }

  Map<String, dynamic> toJson() => {
        'date': date.toIso8601String(),
        'scores': scores.map((k, v) => MapEntry(k.name, v)),
        'notes': notes,
      };

  factory LifeScoreEntry.fromJson(Map<String, dynamic> json) {
    final scoresMap = <LifeDimension, int>{};
    final rawScores = json['scores'] as Map<String, dynamic>;
    for (final dim in LifeDimension.values) {
      scoresMap[dim] = (rawScores[dim.name] as num?)?.toInt() ?? 5;
    }
    return LifeScoreEntry(
      date: DateTime.parse(json['date'] as String),
      scores: scoresMap,
      notes: json['notes'] as String?,
    );
  }
}

/// Focus recommendation generated by analyzing score history.
class FocusRecommendation {
  final LifeDimension dimension;
  final String reason;
  final int priority; // 1 = highest

  FocusRecommendation({
    required this.dimension,
    required this.reason,
    required this.priority,
  });
}

/// Service for life score assessment, persistence, and proactive analysis.
class LifeScoreService {
  static const _storageKey = 'life_score_entries';

  List<LifeScoreEntry> _entries = [];
  List<LifeScoreEntry> get entries => List.unmodifiable(_entries);

  /// Load all entries from persistent storage.
  ///
  /// Routes through [StorageBackend] so life-score data benefits from
  /// the unified sensitivity-aware storage layer.
  Future<void> load() async {
    final raw = await StorageBackend.read(_storageKey);
    if (raw != null && raw.isNotEmpty) {
      final list = jsonDecode(raw) as List;
      _entries = list
          .map((e) => LifeScoreEntry.fromJson(e as Map<String, dynamic>))
          .toList()
        ..sort((a, b) => a.date.compareTo(b.date));
    }
  }

  /// Save a new assessment.
  Future<void> addEntry(LifeScoreEntry entry) async {
    _entries.add(entry);
    _entries.sort((a, b) => a.date.compareTo(b.date));
    await _persist();
  }

  /// Delete an entry by index.
  Future<void> deleteEntry(int index) async {
    if (index >= 0 && index < _entries.length) {
      _entries.removeAt(index);
      await _persist();
    }
  }

  Future<void> _persist() async {
    await StorageBackend.write(
        _storageKey, jsonEncode(_entries.map((e) => e.toJson()).toList()));
  }

  /// Get trend for a dimension over recent entries (positive = improving).
  double trend(LifeDimension dim, {int lookback = 5}) {
    if (_entries.length < 2) return 0;
    final recent = _entries.length > lookback
        ? _entries.sublist(_entries.length - lookback)
        : _entries;
    if (recent.length < 2) return 0;
    // Simple linear regression slope
    double sumX = 0, sumY = 0, sumXY = 0, sumX2 = 0;
    for (int i = 0; i < recent.length; i++) {
      final x = i.toDouble();
      final y = (recent[i].scores[dim] ?? 5).toDouble();
      sumX += x;
      sumY += y;
      sumXY += x * y;
      sumX2 += x * x;
    }
    final n = recent.length.toDouble();
    final denom = n * sumX2 - sumX * sumX;
    if (denom == 0) return 0;
    return (n * sumXY - sumX * sumY) / denom;
  }

  /// Generate proactive focus recommendations based on current scores and trends.
  List<FocusRecommendation> getRecommendations() {
    if (_entries.isEmpty) return [];
    final latest = _entries.last;
    final recs = <FocusRecommendation>[];
    int priority = 1;

    // 1. Declining dimensions
    for (final dim in LifeDimension.values) {
      final t = trend(dim);
      if (t < -0.3) {
        recs.add(FocusRecommendation(
          dimension: dim,
          reason:
              '${dim.label} is trending down (${t.toStringAsFixed(1)}/entry)',
          priority: priority++,
        ));
      }
    }

    // 2. Weak spots in latest assessment
    for (final dim in latest.weakSpots) {
      if (!recs.any((r) => r.dimension == dim)) {
        recs.add(FocusRecommendation(
          dimension: dim,
          reason:
              '${dim.label} scored ${latest.scores[dim]} — well below your average of ${latest.overall.toStringAsFixed(1)}',
          priority: priority++,
        ));
      }
    }

    // 3. High imbalance warning
    if (latest.imbalance > 2.5) {
      final lowest = LifeDimension.values.reduce(
          (a, b) => (latest.scores[a] ?? 0) < (latest.scores[b] ?? 0) ? a : b);
      if (!recs.any((r) => r.dimension == lowest)) {
        recs.add(FocusRecommendation(
          dimension: lowest,
          reason:
              'Your life balance is uneven (σ=${latest.imbalance.toStringAsFixed(1)}). ${lowest.label} needs attention.',
          priority: priority++,
        ));
      }
    }

    return recs;
  }
}
